process.env.DATABASE_URL = 'postgresql://test:test@localhost:5432/fan_sale_test'
process.env.AUTH_JWT_SECRET = 'test-secret-minimum-sixteen-chars'
process.env.FAN_SALE_ENABLED = 'true'
process.env.NODE_ENV = 'test'
process.env.HERMES_SERVICE_URL = 'http://hermes-mock'
process.env.REDIS_URL = 'redis://localhost:6379'
